// This file is generated by build-config.js
// Do not modify manually!

// BEGIN OF GENERATED FILE
window.MnemoLinker = {
		latestVersion: "1.2",
		versions: ["1.0", "1.1", "1.2"]
	};
window.MnemoLinker.versions.forEach(version => {
		const filePath = "./MnemoLinker/MnemoLinker_v" + version + ".js";
		window.MnemoLinker["v" + version] = import(filePath).then(module => module.MnemoLinker);
	});
// END OF GENERATED FILE
